# makefile - LociTerm locid server
# Created: Sun May  1 10:42:59 PM EDT 2022 malakai
# $Id: makefile,v 1.12 2024/12/06 04:59:51 malakai Exp $

# Copyright © 2022 Jeff Jahr <malakai@jeffrika.com>
#
# This file is part of LociTerm - Last Outpost Client Implementation Terminal
#
# LociTerm is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# LociTerm is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with LociTerm.  If not, see <https://www.gnu.org/licenses/>.

# $(LOCI) is the name of the LociTerm server binary. Make install will copy
# it to ../$(LOCI).next so that the guardian script can pick it up on the next
# reboot.
LOCI = locid

# Ideally, this should match the LOCITERM_VERSION in the toplevel makefile.
# When building only the server, derive the core version from the toplevel
# makefile so standalone builds report the real version; the -dev$(TS)
# suffix still marks them as not-the-blessed-full-build. Falls back to a
# hardcoded number only if the toplevel makefile isn't found.
TS = $(shell date +%H%M%S)
TOPLEVEL_CORE := $(shell sed -n 's/^LOCITERM_CORE[[:space:]]*[:?]*=[[:space:]]*//p' ../../makefile 2>/dev/null | sed -e 's/[[:space:]]*\#.*//' -e 's/[[:space:]]*$$//' | head -1)
ifeq ($(TOPLEVEL_CORE),)
LOCITERM_VERSION ?= 2.9.0-dev$(TS)
else
LOCITERM_VERSION ?= $(TOPLEVEL_CORE)-dev$(TS)
endif

# If your version of libwebsocket has a broken permessage-deflate handler (i.e.
# libwebsockets main branch, with git commit
# c60bff09914b02c320ce87898a95e2f85e228af7 applied and neither fixed nor
# reverted yet), uncomment this line, and PMD won't be used.
# LOCI_DISABLE_PMD = 1

# List the LOCI .c files here.  Order doesn't matter.  Dont worry
# about header file dependencies, this makefile will figure them out
# automatically.
LOCI_CFILES = locid.c debug.c proxy.c client.c game.c connect.c telnet.c libtelnet.c gamedb.c iostats.c scan.c charset.c

# The list of HFILES, (required for making the ctags database) is generated
# automatically from the LOCI_CFILES list.  However, not everything in LOCI_CFILES
# has a corresponding .h file.  MISSING_HFILES lists the .h's that aren't
# expected to exist.  ADDITIONAL_HFILES lists the .h's for which no .c exists.
ADDITIONAL_HFILES = loci_tcpinfo.h
MISSING_HFILES = 

# CDEBUG, use -g for gdb symbols.  For gprof, add -pg and -no-pie.
# For ASAN add -fsanitize=address (uses a much larger memory footprint)
# use 'break __sanitizer::Die' inside of gdb to stop on a san error.
# For valgrind performance with kcachegrind run locid with 
#   `valgrind --tool=callgrind --dump-instr=yes --collect-jumps=yes`
#CDEBUG = -g -Og
# CDEBUG = -g  -fsanitize=address
CDEBUG = -g -Og

# CDEFINES, for passing version number in through makefiles.
CDEFINES = -D'LOCITERM_VERSION="$(LOCITERM_VERSION)"' 

ifdef LOCI_DISABLE_PMD
CDEFINES += -DLOCI_DISABLE_PMD
endif

# #### Flags and linklibs definitions ####

# gcc and clang spell this warning suppression differently.  Recursive
# expansion so $(CC) is resolved at use time, after any CC defaulting.
WNO_DISCARDED_QUALIFIERS = $(if $(findstring clang,$(shell $(CC) --version 2>/dev/null)),-Wno-incompatible-pointer-types-discards-qualifiers,-Wno-discarded-qualifiers)

CFLAGS = -I/usr/local/include -Wall $(WNO_DISCARDED_QUALIFIERS) -Wno-unused-variable -Wno-unused-function -Wno-unused-but-set-variable -DHAVE_ZLIB -DHAVE_ZSTD
CFLAGS += `pkg-config --cflags glib-2.0`
CFLAGS += `pkg-config --cflags libwebsockets`
CFLAGS += `pkg-config --cflags json-c`
CFLAGS += `pkg-config --cflags sqlite3`
CFLAGS += `pkg-config --cflags libzstd`



LDFLAGS = -L/usr/local/lib
LINKLIBS = -lz
LINKLIBS += `pkg-config --libs libwebsockets` 
LINKLIBS += `pkg-config --libs glib-2.0`
LINKLIBS += `pkg-config --libs json-c`
LINKLIBS += `pkg-config --libs sqlite3`
LINKLIBS += `pkg-config --libs libuv`
LINKLIBS += `pkg-config --libs libzstd`

# #### ############################################# ###
# ####         Makefile magic begins here.           ###
# #### Very little needs to change beyond this line! ###
# #### ############################################# ###


# Default to gcc, but respect a CC given in the environment or on the
# command line (e.g. 'make CC=cc' for the system compiler on macOS).
ifeq ($(origin CC),default)
CC=gcc
endif
BUILD = ./build

CFILES = $(LOCI_CFILES)

# HFILES generated automatically from CFILES, with additions and exclusions
HFILES := $(ADDITIONAL_HFILES)
HFILES += $(addsuffix .h, $(basename $(CFILES)))
HFILES := $(filter-out $(MISSING_HFILES), $(HFILES))

LOCI_OFILES = $(LOCI_CFILES:%.c=$(BUILD)/%.o)
OFILES = $(LOCI_OFILES)

LOCI_DFILES = $(LOCI_CFILES:%.c=$(BUILD)/%.d)
DFILES = $(LOCI_DFILES)

RUN = .

# #### Recipies Start Here ####

$(info ---------- START OF LOCID COMPILATION -----------)
all : $(BUILD) run tags

# Copying the binaries...
#.PHONY: $(LOCI)
$(LOCI) : $(BUILD) $(BUILD)/$(LOCI)

.PHONY: run
run : $(LOCI) $(RUN)/$(LOCI)

# The mv command is to prevent 'text file busy' error, and the 2>/ is some bash
# bullshit to keep the command from failing the make if the source file doesn't
# exist.
$(RUN)/$(LOCI) : $(BUILD)/$(LOCI)
	-mv -f $(RUN)/$(LOCI) $(RUN)/$(LOCI).prev 2>/dev/null || true
	cp $(BUILD)/$(LOCI) $(RUN)/$(LOCI)

# Create build directory...
$(BUILD) : 
	mkdir -p $(BUILD)

# Create run directory...
$(RUN) : 
	mkdir -p $(RUN)

# Linking the LOCI binary...
$(BUILD)/$(LOCI) : $(LOCI_OFILES)
	$(CC) $(CDEBUG) $(CDEFINES) $(LDFLAGS) $^ -o $(@) $(LINKLIBS)

# check the .h dependency rules in the .d files made by gcc
-include $(LOCI_DFILES)

# Build the .o's from the .c files, building .d's as you go.
$(BUILD)/%.o : %.c
	$(CC) $(CDEBUG) $(CDEFINES) $(CFLAGS) -MMD -c $< -o $(@)

# Updating the tags file...  The - keeps a missing or incompatible ctags
# (e.g. the BSD one on macOS) from failing the build.
tags : $(HFILES) $(CFILES)
	-ctags $(HFILES) $(CFILES)

# Cleaning up...
# .PHONY just means 'not really a filename to check for'
.PHONY: clean
clean : 
	-rm $(BUILD)/$(LOCI) $(LOCI) $(OFILES) $(DFILES) tags
	-rmdir $(BUILD)

install: $(LOCI) 
	$(info ---- Not written yet! ----)

.PHONY: wall-summary
wall-summary: 
	$(info ** Enable these errors in the CFLAGS section to track them down. )
	$(info ** Run this after a make clean for full effect! )
	make "CFLAGS=-Wall" 2>&1 | egrep -o "\[-W.*\]" | sort | uniq -c | sort -n

